<a href="https://colab.research.google.com/github/SahilRaut80/Assignments/blob/main/Data_Structures_Functions_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Section A: Data Structures & Control Structures

In [ ]:
# Question 1
a = [1,2,3,4,5]
a.append(6)
print(a)

a.extend([7])
print(a)

a.insert(7,8)
print(a)

a.remove(8)
print(a)

a.pop()
print(a)

print(a.index(3))


print(a.count(4))

a = [1,9,6,4,5]
a.sort(reverse=True)
print(a)

a.reverse()
print(a)


[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6]
2
1
[9, 6, 5, 4, 1]
[1, 4, 5, 6, 9]


In [ ]:
# Question 2
name_tuple = ('om','atharv','sanket')
# tuple is immutable, can't change the vaule in tuple

In [ ]:
# Question 3
sets = {1,2,3,4,3,5,3}
print(sets)

# set always give the unique vales


{1, 2, 3, 4, 5}


In [ ]:
# Question 4
dictionary = {'name':'om','age':20,'city':'pune'}

dictionary['age']=21
dictionary['email']='max@gmail.com'

print(dictionary)

{'name': 'om', 'age': 21, 'city': 'pune', 'email': 'max@gmail.com'}


In [ ]:
# Question 5
age = int(input('Enter age '))

if age >= 18 :
  print('eligible to vote')
else:
  ('not eligible')

Enter age 20
eligible to vote


In [ ]:
# Question 6
marks = int(input('Enter marks '))

if marks >= 90:
  print('Grade A')
elif marks >= 75:
  print('Grade B')
elif marks >= 50:
  print('Grade C')
else:
  print('Fail')

Enter marks 91
Grade A


In [ ]:
# Question 7

num = int(input('Enter number '))

if num > 0:
  if num % 2 == 0:
    print('number number is even and positive')
  else:
    print('number is positive but not even')
elif num ==0:
  print('number is zero')
else:
  print('number is negative')


Enter number 2
number number is even and positive


Section B: Numpy


In [ ]:
# Question 8

import numpy as np
a = np.array(5)

one_d_arr = np.arange(1,6)

two_d_arr = np.arange(10, 61, 10).reshape(2, 3)


print(a)
print(one_d_arr)
print(two_d_arr)

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


In [ ]:
# Question 9

x = np.random.randint(0,100, size=(4,4))
x

array([[91, 22, 59, 77],
       [65,  9, 61, 17],
       [96, 76, 79, 44],
       [ 9, 63, 89, 63]])

In [ ]:
# Question 10
import pandas as pd

data = np.array([[1,2,3],[4,5,6],[7,8,9]])

df = pd.DataFrame(data, columns=['A','B','C'])
df


,A,B,C
0,1,2,3
1,4,5,6
2,7,8,9


Section C: Exploring Pandas

In [ ]:
# Question 11


data = {
    'Name': ['Alice', 'Alice', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'],
    'Age':[10,10,45,34,54,34,43,33,24,54],
    'City': ['New York', 'New York', 'London', 'Tokyo', 'Berlin', 'New York', 'London', 'Paris', 'Tokyo', 'Berlin'],
    'Salary': [70000, 70000, 60000, 95000, 80000, 110000, 75000, None, 82000, 88000]
    }

df = pd.DataFrame(data)
print(df)


      Name  Age      City    Salary
0    Alice   10  New York   70000.0
1    Alice   10  New York   70000.0
2  Charlie   45    London   60000.0
3    David   34     Tokyo   95000.0
4      Eva   54    Berlin   80000.0
5    Frank   34  New York  110000.0
6    Grace   43    London   75000.0
7    Henry   33     Paris       NaN
8      Ivy   24     Tokyo   82000.0
9     Jack   54    Berlin   88000.0


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [ ]:
df.describe()

,Age,Salary
count,10.000000,9.000000
mean,34.100000,81111.111111
std,15.828596,15028.676293
min,10.000000,60000.000000
25%,26.250000,70000.000000
50%,34.000000,80000.000000
75%,44.500000,88000.000000
max,54.000000,110000.000000


In [ ]:
df[['Name', 'City']]

,Name,City
0,Alice,New York
1,Alice,New York
2,Charlie,London
3,David,Tokyo
4,Eva,Berlin
5,Frank,New York
6,Grace,London
7,Henry,Paris
8,Ivy,Tokyo
9,Jack,Berlin


In [ ]:
df.drop(columns = ['City'])

,Name,Age,Salary
0,Alice,10,70000.0
1,Alice,10,70000.0
2,Charlie,45,60000.0
3,David,34,95000.0
4,Eva,54,80000.0
5,Frank,34,110000.0
6,Grace,43,75000.0
7,Henry,33,NaN
8,Ivy,24,82000.0
9,Jack,54,88000.0


In [ ]:
df['Salary'].fillna(df['Salary'].mean(), inplace = True)
df

/tmp/ipykernel_748/3912328046.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace = True)


,Name,Age,City,Salary
0,Alice,10,New York,70000.000000
1,Alice,10,New York,70000.000000
2,Charlie,45,London,60000.000000
3,David,34,Tokyo,95000.000000
4,Eva,54,Berlin,80000.000000
5,Frank,34,New York,110000.000000
6,Grace,43,London,75000.000000
7,Henry,33,Paris,81111.111111
8,Ivy,24,Tokyo,82000.000000
9,Jack,54,Berlin,88000.000000


In [ ]:
df.drop_duplicates()

,Name,Age,City,Salary
0,Alice,10,New York,70000.000000
2,Charlie,45,London,60000.000000
3,David,34,Tokyo,95000.000000
4,Eva,54,Berlin,80000.000000
5,Frank,34,New York,110000.000000
6,Grace,43,London,75000.000000
7,Henry,33,Paris,81111.111111
8,Ivy,24,Tokyo,82000.000000
9,Jack,54,Berlin,88000.000000
